name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure node
        uses: actions/setup-node@master
        with:
          node-version: "10.x"

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Prepare GITHUB_TOKEN
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Publish
        run: yarn publish

      - name: Storybook
        run: yarn storybook

      - name: Configure GIT
        run: |
          git config --global user.email "<>"
          git config --global user.name "Storybook Publisher"

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: gurunars
          TITLE: spikard
        run: |
          mv ./dist /tmp
          cd /tmp/dist

          git init
          git add .
          git commit -am init
          git push --force https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${USERNAME}/${TITLE}.git gh-pages
