name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure node
        uses: actions/setup-node@master
        with:
          node-version: "10.x"

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Prepare GITHUB_TOKEN
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Publish
        run: yarn publish

